### ISSUE TITLE
Backspace Not working in mobile devices

### ISSUE THREAD

**Issue by sugam-techuz** [code-farmz/ng-otp-input#3] opened 2019-07-12 12:16 UTC
In mobile devices when we try to delete inserted otp code, its not allowed to delete previous digit. Its not working like desktop browser.

**Comment by niravgoswami12** [comment] 2019-07-12 12:19
Hi,
Also facing same issue

**Comment by code-farmz** [comment] 2019-07-12 12:28
@sugam-techuz  can you please post the exact steps to reproduce what I tried is 

1.entered the otp 
2.press delete button it was working as aspected

or it may be device specific

**Comment by niravgoswami12** [comment] 2019-07-12 12:59
![WhatsAppVideo2019-07-12at62](https://user-images.githubusercontent.com/13786391/61129836-ec890180-a4d2-11e9-897c-9483ad8bf8e0.gif)
Please check

**Comment by sugam-techuz** [comment] 2019-07-12 13:20
Yes, i have same thing happen in mobile.
when we click on backspace it's not delete previous box value.

**Comment by code-farmz** [comment] 2019-07-12 14:00
@niravgoswami12  @sugam-techuz  seems like device specific issue if you specify the device here

**Comment by sugam-techuz** [comment] 2019-07-15 05:33
@code-farmz 
Divice : Redmi Note 5 pro, Android 9.

**Comment by code-farmz** [comment] 2019-07-15 05:56
Hi thanks for the update I'll check it out and let you know if I am able to reproduce this one

**Comment by code-farmz** [comment] 2019-07-19 12:11
Tested on redmi note 5,6,7 and seems to be working fine with new version so closing it for now

**Closed by code-farmz** 2019-07-19 12:11 UTC
