### ISSUE TITLE
Null Injection Error Angular 13

### ISSUE THREAD

**Issue by nickLiechti** [code-farmz/ng-otp-input#90] opened 2022-04-04 08:55 UTC
I Get the Error :  
  ERROR NullInjectorError: R3InjectorError(AppModule)[KeysPipe -> KeysPipe -> KeysPipe]: 
  NullInjectorError: No provider for KeysPipe!

When importing ng-otp-input

In Angular 13

**Comment by code-farmz** [comment] 2022-04-06 04:21
@nickLiechti  can you please provide stackblitz example for the problem

**Comment by code-farmz** [comment] 2023-05-24 08:30
closing this as didn't hear back and not able to reproduce

**Closed by code-farmz** 2023-05-24 08:30 UTC
